name: Build and Deploy

on:
  push:
    branches:
      - main  # Triggers the workflow when there's a push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # You can specify the Node.js version here

      # Step 3: Navigate to the `playground/chat` directory
      - name: Change directory to chat
        working-directory: playground/chat
        run: echo "Moved to playground/chat directory"

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: playground/chat
        run: npm install

      # Step 5: Build the package
      - name: Build the package
        working-directory: playground/chat
        run: npm run build

      # Step 6: Deploy the `dist` folder to the build branch
      - name: Deploy to build branch
        working-directory: playground/chat
        run: |
          git config --global user.email "elaloglens@gmail.com"
          git config --global user.name "Lalolens"
          git checkout --orphan build  # Create a new branch detached from history
          git reset --hard  # Clear all current files from the working tree
          # Copy required files to root for the build branch
          mkdir -p dist
          cp -r playground/chat/dist/* dist/
          cp playground/chat/package.json package.json
          cp playground/chat/README.md README.md
          cp playground/chat/LICENSE LICENSE
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Deploy build"
            git push --force --set-upstream origin build
          else
            echo "No changes to deploy"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
